server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG #

spring:
  security:
    user:
      password: root
      name: root
      roles: # multiple roles can be defined
        - ADMIN
        - USER
